greatly refine

diff --git a/spotbash b/spotbash
--- a/spotbash
+++ b/spotbash
@@ -7,24 +7,25 @@ has() {
     alias*|"") return 1
   esac
 }
+cat() {
+  [ "$1" ] && {
+    while read -r p || [ "$p" ]; do
+      printf '%s\n' "$p"
+    done < $1 
+  } || {
+    while read -r p || [ -n $p ]; do
+      printf '%s\n' "$p"
+    done
+  }
+}
 deps() {
-  deps="jq curl" # Make sure deps can be found
+  unset IFS
+  deps="jq curl"; missing=0 # Make sure deps can be found
   for i in $deps; do
     if ! has $i; then
-      echo "$i IS MISSING!"; missing=$(($missing + 1))
+      echo "$i IS MISSING!"; : $((missing+=1))
     fi
-  done
-  [ ${missing:-0} -gt 0 ] || {
-    [ ${missing:-0} -gt 1 ] && {
-      echo "JQ AND CURL ARE MISSING!"; exit 1
-    } || {
-      for i in $deps; do
-        if ! has $i; then
-          echo "$i IS MISSING!"; exit 1
-        fi
-      done
-    }
-  }
+  done; [ $missing -gt "0" ] && exit 1
   # Check for ssl
   curl -V | grep tls -i -q || {
     curl -V | grep ssl -i -q || {
@@ -42,15 +43,15 @@ clean_up(){
   done
 }
 auth() {
-  if [ ! -f "${XDG_CACHE_HOME:-$HOME/.cache/}/spotbash/authkeys" ];then
-    { [ -f ./authkeys ] && . ./authkeys; } || {
-      echo "ERROR: The AUTHKEYS cache file is missing!! Spotbash needs this file.. If you don't have it, reclone and re-run the setup"; exit 1
-    }
-  else
-    . "${XDG_CACHE_HOME:-$HOME/.cache/}/spotbash/authkeys"
-  fi
+  IFS=""; # eval $(cat) # eval STDIN - allows for authkeys to be passed via STDIN 
+  # above needs a way to check if reading from STDIN
+  [ "$REKEY" -a "$CLID" -a "$CLSEC" ] || for i in ./authkeys "${0%/*}/authkeys" "${XDG_CACHE_HOME:-$HOME/.cache/}/spotbash/authkeys"; do # only run loop all variables for AUTHKEY are unset
+    [ -e $i -a ! "$REKEY" ] && . ${i}
+  done # much cleaner then old method
+  
+
   AUTHKEY=$(curl -X POST -d grant_type=refresh_token -d refresh_token="$REKEY" -d client_id="$CLID" -d client_secret="$CLSEC" https://accounts.spotify.com/api/token -s | jq .access_token -r)
-  export AUTHKEY; export AUTHD="1"
+  export AUTHKEY
 }
 get_info(){
   curl -s -X "GET" "https://api.spotify.com/v1/me/player" -H "Accept: application/json" -H "Content-Type: application/json" -H "Authorization: Bearer $AUTHKEY" > "${XDG_CACHE_HOME:-$HOME/.cache/}/spotbash/info"
@@ -84,7 +85,7 @@ name(){
     }
   }
   cat $artemp ; rm $artemp -rf
-}
+} # TODO - FIXME # using mktemp is bad practice
 get_volume(){
   jq .device.volume_percent < "$infoF"
 }
@@ -110,24 +111,13 @@ devices(){
 set_volume(){
     curl -s -X PUT -d device_id="$id" -H "Accept: application/json" -H "Content-Type: application/json" -H "Authorization: Bearer $AUTHKEY" "https://api.spotify.com/v1/me/player/volume?volume_percent=$2"
 }
-search_track(){
-    IFS=""
+search_track(){ # only searching tracks is currently supported 
+    IFS=""; set -f # globbing is bad here
     [ -f "${XDG_CACHE_HOME:-$HOME/.cache/}/spotbash/search" ] && . "${XDG_CACHE_HOME:-$HOME/.cache/}/spotbash/search" || search="$2"
-    { echo "$search" | grep -q '[[:space:]]'; } && search=$(printf '%s' "$search" | sed -E 's/[[:space:]]/%20/g')
-    curl -s X "GET" -H "Accept: application/json" -H "Content-Type: application/json" -H "Authorization: Bearer $AUTHKEY" "https://api.spotify.com/v1/search?q=${search}&limit=9&type=track" | jq '.tracks.items,del(.[]) | .[] | .name,[.artists[].name],.uri' -r -M | sed -E -e '/\[/d' -e '/\]/d' -e 's/[[:blank:]]"/By\: /g' -e 's/"//g' | tr '\n' '~' | sed -E -e 's/~spotify\:/ @ spotify\:/g' -e 's/~ By\:/ By:/g' | tr '~' '\n'
+    { printf '%s' "${search}" | grep -q ' '; } && export search="$(printf '%s' "${search}" | sed -E 's/[[:space:]]/%20/g')" # grep '[[:space:]]' may fail here
+    curl -sX "GET" -H "Accept: application/json" -H "Content-Type: application/json" -H "Authorization: Bearer $AUTHKEY" "https://api.spotify.com/v1/search?q=$search&limit=9&type=track" | jq '.tracks.items,del(.[]) | .[] | .name+" By: "+.artists[].name+" @ "+.uri' -r -M
+    set +f
 }
-#search_album(){
-#    IFS=""
-#    if [ -f "${XDG_CACHE_HOME:-$HOME/.cache/}/spotbash/search" ]; then
-#        source "${XDG_CACHE_HOME:-$HOME/.cache/}/spotbash/search"
-#    else
-#        search="$2"
-#    fi
-#    if ! echo "$search" | grep -q '[[:space:]]'; then
-#      search=$(printf '%s' "$search" | sed -E 's/[[:space:]]/%20/g')
-#    fi
-#    curl -s =X "GET" -H "Accept: application/json" -H "Content-Type: application/json" -H "Authorization: Bearer $AUTHKEY" "https://api.spotify.com/v1/search?q=${search}&limit=9&type=album" | jq '.[] | .items | .[] | .["name"],[ .artists | .[] | .name ],.["uri"]' | sed -E -e 's/\[//g' -e 's/\]//g' -e '/^[[:space:]]*$/d' -e 's/,//g' -e 's/"//g' -e '/^ *$/d' | sed -E -z -e 's/\n  /  By: /g' -e 's/\nspotify:/ @ spotify:/g'
-#} POSIX SED PAIN
 play_track(){
   [ -f "${XDG_CACHE_HOME:-$HOME/.cache/}/spotbash/uri" ] && . "${XDG_CACHE_HOME:-$HOME/.cache/}/spotbash/uri" || uri="$2"
   curl -s -X PUT "https://api.spotify.com/v1/me/player/play?device_${id}" --data "{\"uris\":[\"$uri\"]}" -H "Accept: application/json" -H "Content-Type: application/json" -H "Authorization: Bearer $AUTHKEY"
