Heres some edits to make the code better, idk I might un-archive this

diff --git a/spotbash b/spotbash
--- a/spotbash
+++ b/spotbash
@@ -1,21 +1,22 @@
 #!/usr/bin/env bash
-. ${XDG_CACHE_HOME:-$HOME/.cache/}/spotbash/authkeys
-if [ ! -f $(which jq) ]; then
+if [ ! -f "${XDG_CACHE_HOME:-$HOME/.cache/}"/spotbash/authkeys ];then
+	. "$(find "${XDG_HOME:-$HOME}" | grep "potbash/authkeys" | cut -d$'\n' -f2-)"
+	# Just going to source whatever looks like Spotbash's autokeys config file if we can;t find it
+else
+	. "${XDG_CACHE_HOME:-$HOME/.cache/}"/spotbash/authkeys
+fi
+if [ ! -f "$(which jq)" ]; then
     echo "jq not found!"
     exit 1
 fi
-if [ ! -f $(which curl) ]; then
+if [ ! -f "$(which curl)" ]; then
     echo "curl not found!"
     exit 1
 fi
 export AUTHKEY="" 
-#refresh(){
-#    curl -X POST -d grant_type=refresh_token -d refresh_token=$rekey https://accounts.spotify.com/api/token -s | jq '.access_token' | sed 's/"//g'
-#}
-#while sleep 1h; do refresh ;done &
 # For right now we get a new oauthkey everytime we use spotbash; the oauth key only lasts 1 hour, while the $REKEY is infinite
 get_info(){
-    curl -s -X "GET" "https://api.spotify.com/v1/me/player" -H "Accept: application/json" -H "Content-Type: application/json" -H "Authorization: Bearer $AUTHKEY" # | sed '/},/q' | sed -e 's/},/}\n\}/g' 
+    curl -s -X "GET" "https://api.spotify.com/v1/me/player" -H "Accept: application/json" -H "Content-Type: application/json" -H "Authorization: Bearer $AUTHKEY"
 }
 select_sh(){
 		sed '/},/q' | sed -e 's/},/}\n\}/g'
@@ -23,22 +24,22 @@ select_sh(){
 get_volume(){
     get="volume_percent"
     IFS="" # IFS breaks 'echo $(jq)'
-    echo $(get_info) | select_sh | jq '.device' | jq ".$get"
+    get_info | select_sh | jq '.device' | jq ".$get"
 }
 pause(){
-    curl -X PUT -s -d device_id=$id -H "Accept: application/json" -H "Content-Type: application/json" -H "Authorization: Bearer $AUTHKEY" https://api.spotify.com/v1/me/player/pause
+    curl -X PUT -s -d device_id="$id" -H "Accept: application/json" -H "Content-Type: application/json" -H "Authorization: Bearer $AUTHKEY" https://api.spotify.com/v1/me/player/pause
 }
 resume(){
     curl -s --fail -X PUT --data "{}" -H "Accept: application/json" -H "Content-Type: application/json" -H "Authorization: Bearer $AUTHKEY" https://api.spotify.com/v1/me/player/play
 }
 next(){
-    curl -X "POST" -s -d device_id=$id -H "Accept: application/json" -H "Content-Type: application/json" -H "Authorization: Bearer $AUTHKEY" https://api.spotify.com/v1/me/player/next
+    curl -X "POST" -s -d device_id="$id" -H "Accept: application/json" -H "Content-Type: application/json" -H "Authorization: Bearer $AUTHKEY" https://api.spotify.com/v1/me/player/next
 }
 skip(){
     next
 }
 previous(){
-     curl -X "POST" -s -d device_id=$id -H "Accept: application/json" -H "Content-Type: application/json" -H "Authorization: Bearer $AUTHKEY" https://api.spotify.com/v1/me/player/previous
+     curl -X "POST" -s -d device_id="$id" -H "Accept: application/json" -H "Content-Type: application/json" -H "Authorization: Bearer $AUTHKEY" https://api.spotify.com/v1/me/player/previous
 }
 pre(){
 		 previous
@@ -51,38 +52,39 @@ devices(){
     curl -X "GET" "https://api.spotify.com/v1/me/player/devices" -H "Accept: application/json" -H "Content-Type: application/json" -H "Authorization: Bearer  $AUTHKEY" -s | jq '.[]' | sed -z 's/]\n.*/]/g' | jq '.[]' | jq '.name,.id' | sed 's/"//g'
 }
 set_volume(){
-    curl -s -X PUT -d device_id=$id -H "Accept: application/json" -H "Content-Type: application/json" -H "Authorization: Bearer $AUTHKEY" "https://api.spotify.com/v1/me/player/volume?volume_percent=$2"
+    curl -s -X PUT -d device_id="$id" -H "Accept: application/json" -H "Content-Type: application/json" -H "Authorization: Bearer $AUTHKEY" "https://api.spotify.com/v1/me/player/volume?volume_percent=$2"
 }
 search_track(){
     IFS=""
-    if [ -f ${XDG_CACHE_HOME:-$HOME/.cache/}/spotbash/search ]; then
-        source ${XDG_CACHE_HOME:-$HOME/.cache/}/spotbash/search
+    if [ -f "${XDG_CACHE_HOME:-$HOME/.cache/}"/spotbash/search ]; then
+        source "${XDG_CACHE_HOME:-$HOME/.cache/}"/spotbash/search
     else
         search="$2"
     fi
-    if [ ! $(echo $search | grep -q '[[:space:]]') ]; then
-      search=$(echo -n $search | sed 's/[[:space:]]/%20/g')
+    if [ ! $(echo "$search" | grep -q '[[:space:]]') ]; then
+      search=$(echo -n "$search" | sed 's/[[:space:]]/%20/g')
     fi
     curl -s X "GET" -H "Accept: application/json" -H "Content-Type: application/json" -H "Authorization: Bearer $AUTHKEY" "https://api.spotify.com/v1/search?q=${search}&limit=9&type=track" | jq '.tracks' | jq '.items,del(.[]) | [.[] | .name,[.artists | .[] | .["name"]],.uri]' |  sed -z 's/\[]\n//g' | sed -e 's/\[//g' -e 's/]//g' -e '/^[[:space:]]*$/d' -e 's/,//g' -e 's/  "//g' -e 's/"//g' -e '/^ *$/d' | sed -z -e 's/\n  /  By: /g' -e 's/\nspotify:/ @ spotify:/g'
 }
 search_album(){
         IFS=""
-    if [ -f ${XDG_CACHE_HOME:-$HOME/.cache/}/spotbash/search ]; then
-        source ${XDG_CACHE_HOME:-$HOME/.cache/}/spotbash/search
+    if [ -f "${XDG_CACHE_HOME:-$HOME/.cache/}"/spotbash/search ]; then
+        source "${XDG_CACHE_HOME:-$HOME/.cache/}"/spotbash/search
     else
         search="$2"
     fi
-    if [ ! $(echo $search | grep -q '[[:space:]]') ]; then
-      search=$(echo -n $search | sed 's/[[:space:]]/%20/g')
+    if [ ! $(echo "$search" | grep -q '[[:space:]]') ]; then
+      search=$(echo -n "$search" | sed 's/[[:space:]]/%20/g')
     fi
     curl -s X "GET" -H "Accept: application/json" -H "Content-Type: application/json" -H "Authorization: Bearer $AUTHKEY" "https://api.spotify.com/v1/search?q=${search}&limit=9&type=album" | jq '.[] | .items | .[] | .["name"],[ .artists | .[] | .name ],.["uri"]' | sed -e 's/\[//g' -e 's/\]//g' -e '/^[[:space:]]*$/d' -e 's/,//g' -e 's/"//g' -e '/^ *$/d' | sed -z -e 's/\n  /  By: /g' -e 's/\nspotify:/ @ spotify:/g'
 }
 auth(){
-  export AUTHKEY=$(curl -X POST -d grant_type=refresh_token -d refresh_token=$REKEY -d client_id=$CLID -d client_secret=$CLSEC https://accounts.spotify.com/api/token -s | jq .access_token | sed 's/"//g')
+  AUTHKEY=$(curl -X POST -d grant_type=refresh_token -d refresh_token="$REKEY" -d client_id="$CLID" -d client_secret="$CLSEC" https://accounts.spotify.com/api/token -s | jq .access_token | sed 's/"//g')
+  export AUTHKEY
 }
 play_track(){
-    if [ -f ${XDG_CACHE_HOME:-$HOME/.cache/}/spotbash/uri ]; then
-        source ${XDG_CACHE_HOME:-$HOME/.cache/}/spotbash/uri
+    if [ -f "${XDG_CACHE_HOME:-$HOME/.cache/}"/spotbash/uri ]; then
+        source "${XDG_CACHE_HOME:-$HOME/.cache/}"/spotbash/uri
     else
         uri="$2"
     fi  
@@ -92,13 +94,13 @@ state(){
 	get_info | jq 'del(.["device", "actions", "external_urls", "track_number", "preview_url", "popularity", "name", "uri", "href", "id", "is_local", "item", "shuffle_state", "repeat_state", "timestamp", "context", "progress_ms", "currently_playing_type"])' | sed -e '/}/d' -e '/{/d' | sed 's/"//g' | sed 's/\s\sis_playing/Playing/g'
 }
 loop(){
-    curl -X "PUT" -d device_id=$id -H "Accept: application/json" -H "Content-Type: application/json" -H "Authorization: Bearer $AUTHKEY" "https://api.spotify.com/v1/me/player/repeat?state=track"
+    curl -X "PUT" -d device_id="$id" -H "Accept: application/json" -H "Content-Type: application/json" -H "Authorization: Bearer $AUTHKEY" "https://api.spotify.com/v1/me/player/repeat?state=track"
 }
 repeat(){
-    curl -X "PUT" -d device_id=$id -H "Accept: application/json" -H "Content-Type: application/json" -H "Authorization: Bearer $AUTHKEY" "https://api.spotify.com/v1/me/player/repeat?state=context"
+    curl -X "PUT" -d device_id="$id" -H "Accept: application/json" -H "Content-Type: application/json" -H "Authorization: Bearer $AUTHKEY" "https://api.spotify.com/v1/me/player/repeat?state=context"
 }
 repeat_off(){
-    curl -X "PUT" -d device_id=$id -H "Accept: application/json" -H "Content-Type: application/json" -H "Authorization: Bearer $AUTHKEY" "https://api.spotify.com/v1/me/player/repeat?state=off"
+    curl -X "PUT" -d device_id="$id" -H "Accept: application/json" -H "Content-Type: application/json" -H "Authorization: Bearer $AUTHKEY" "https://api.spotify.com/v1/me/player/repeat?state=off"
 }
 repeat_state(){
     get_info | jq 'del(.["device", "actions", "external_urls", "track_number", "preview_url", "popularity", "name", "uri", "href", "id", "is_local", "item", "shuffle_state", "is_playing", "timestamp", "context", "progress_ms", "currently_playing_type"])' | sed -e '/{/d' -e '/}/d' -e 's/"//g' -e 's/\s\srepeat_state/Loop State/g'
@@ -148,28 +150,33 @@ kill_node: Can be used to quickly kill any node processes | used to kill SDK ser
 ***
 EOF
 }
-auth
-id=$(curl -X "GET" "https://api.spotify.com/v1/me/player/devices" -H "Accept: application/json" -H "Content-Type: application/json" -H "Authorization: Bearer  $AUTHKEY" -s | jq '.["devices"][].id' | sed 's/"//g')
-if [ $1 = "auth" ]; then
-    echo $AUTHKEY
-    exit 0
-fi
-if [ $1 = "search_play" ]; then
-    printf "search='%b'" "${2}" > ${XDG_CACHE_HOME:-$HOME/.cache/}/spotbash/search
-    sed -i -e 's/ /%20/g' ${XDG_CACHE_HOME:-$HOME/.cache/}/spotbash/search
-    uri=$(search | sed -e 's/Name:.*//g' -e 's/uri:[[:space:]]//g' -e '/^[[:space:]]*$/d')
-    printf "uri='%b'" "${uri}" > ${XDG_CACHE_HOME:-$HOME/.cache/}/spotbash/uri
-    play_track
-    exit 0
-fi
-if ! type ${1} &>/dev/null ; then
-    help && exit 1
-else
-    if ! ${1} "$@"; then
-       echo "ERROR: Something went wrong!"
-       echo "Possible issues are:"
-       echo "1. A device may not currently be seleted"
-       echo "2. The current user does not have Premium"
-       echo "3. There is no connection"
-    fi
-fi
+id=$(auth && curl -X "GET" "https://api.spotify.com/v1/me/player/devices" -H "Accept: application/json" -H "Content-Type: application/json" -H "Authorization: Bearer  $AUTHKEY" -s | jq '.["devices"][].id' | sed 's/"//g')
+case $1 in
+    auth)
+        auth && echo "$AUTHKEY" && exit 0
+        ;;
+    search_play)
+	 printf "search='%b'" "${2}" > "${XDG_CACHE_HOME:-$HOME/.cache/}"/spotbash/search
+	 sed -i -e 's/ /%20/g' "${XDG_CACHE_HOME:-$HOME/.cache/}"/spotbash/search
+	 uri=$(search | sed -e 's/Name:.*//g' -e 's/uri:[[:space:]]//g' -e '/^[[:space:]]*$/d')
+	 printf "uri='%b'" "${uri}" > "${XDG_CACHE_HOME:-$HOME/.cache/}"/spotbash/uri
+	 play_track "$@"
+	 exit 0
+	 ;;
+    "")
+	help && exit 1
+	;;
+    *)
+        auth && if ! type ${1} &>/dev/null ; then
+   		  help && exit 1
+		else
+    		  if ! ${1} "$@"; then
+       			echo "ERROR: Something went wrong!"
+       			echo "Possible issues are:"
+       			echo "1. A device may not currently be seleted"
+       			echo "2. The current user does not have Premium"
+		        echo "3. There is no connection"
+    		  fi
+                fi
+        ;;
+esac
