v0.4.3 ~ Hopefully is works now :<

diff --git a/spotbash b/spotbash
--- a/spotbash
+++ b/spotbash
@@ -148,11 +148,14 @@ if [ $1 = "search_play" ]; then
     play_track
     exit 0
 fi
-${1} $@
-if [ $? != "0" ]; then
-    echo "ERROR: Something went wrong!"
-    echo "Possible issues are:"
-    echo "1. A device may not currently be seleted"
-    echo "2. The current user does not have Premium"
-    echo "3. There is no connection"
+if ! type ${1} &>/dev/null ; then
+    help && exit 1
+else
+    if ! ${1} $@; then
+       echo "ERROR: Something went wrong!"
+       echo "Possible issues are:"
+       echo "1. A device may not currently be seleted"
+       echo "2. The current user does not have Premium"
+       echo "3. There is no connection"
+    fi
 fi
