Added shuffle func, also, development is on again, I'm just slow

diff --git a/spotbash b/spotbash
--- a/spotbash
+++ b/spotbash
@@ -151,11 +151,33 @@ trans(){
     fi
     curl -X "PUT" "https://api.spotify.com/v1/me/player" --data "{\"device_ids\":[\"${TRANS_ID}\"]}" -H "Accept: application/json" -H "Content-Type: application/json" -H "Authorization: Bearer $AUTHKEY"
 }
+shuffle_state(){
+    get_info | jq .shuffle_state | sed '1 i\Shuffle: ' | tr -d "\n" && printf '\n'
+}
+shuffle() { # FIXME ~ There has to be a better way to do this...
+    if [ ! -z "$2" ]; then
+        shvalue_pre=$(shuffle_state | cut -d' ' -f2-)
+        case $shvalue_pre in
+            true)
+                shvalue="false";;
+            false)
+                shvalue="true";;
+            *)
+                echo "Could not determine the current shuffle state! :("
+                echo "Try again later or use 'arg2' (See help)" && exit 1
+                ;;
+        esac
+        
+    else
+    	shvalue=${2}
+    fi
+    curl -X "PUT" "https://api.spotify.com/v1/me/player/shuffle?state=${shvalue}" -H "Accept: application/json" -H "Content-Type: application/json" -H "Authorization: Bearer $AUTHKEY"
+}
 help(){
 cat << 'EOF'
 Spotbash: Spotify Control API ~ Written in bash ~ By ThatGeekyWeeb (Mia)
 Usage: spotbash:
-[auth|device|search_*|play_track|*_volume|get_info|pre|trans|skip|pause|resume|loop|repeat|state|set|play*|*left*]
+[auth|device|search_*|play_track|*_volume|get_info|pre|trans|skip|pause|resume|loop|repeat|state|set|play*|*left|shuffle*]
 ***
 auth: Print $AUTHKEY and exit
 device: Print first device ID and exit
@@ -183,8 +205,16 @@ play: Play "arg2" | "arg2" must be Album or Playlist URI
 playing: Print Song name followed by artist and exit
 left: Print time left in MS (exact) and exit
 minleft: Print time left in Mins (approximate) and exit
+shuffle: Enable/Disable Shuffle | Set to "arg2" if specified
+shuffle_state: Print state of shuffle and exit
+***
+"arg2" Usage:
+<command> <"arg2">
+IE: search_play "Man of The Year"
+NOTE: Use qoutes!
 ***
 EOF
+# Really important that you use qoutes with "arg2"!!!
 }
 clean_up # Cleaning before doing anything is prob good idea
 case $1 in
