Changed Scopes (Added Web SDK support) ~ Added set, devices & and error handling for resume

diff --git a/spotbash b/spotbash
--- a/spotbash
+++ b/spotbash
@@ -29,7 +29,7 @@ pause(){
     curl -X PUT -s -d device_id=$id -H "Accept: application/json" -H "Content-Type: application/json" -H "Authorization: Bearer $AUTHKEY" https://api.spotify.com/v1/me/player/pause
 }
 resume(){
-    curl -X PUT --data "{}" -H "Accept: application/json" -H "Content-Type: application/json" -H "Authorization: Bearer $AUTHKEY" https://api.spotify.com/v1/me/player/play
+    curl --silent --show-error --fail -X PUT --data "{}" -H "Accept: application/json" -H "Content-Type: application/json" -H "Authorization: Bearer $AUTHKEY" https://api.spotify.com/v1/me/player/play
 }
 next(){
     curl -X "POST" -s -d device_id=$id -H "Accept: application/json" -H "Content-Type: application/json" -H "Authorization: Bearer $AUTHKEY" https://api.spotify.com/v1/me/player/next
@@ -45,6 +45,10 @@ pre(){
 }	
 device(){
      echo "Device_${id}"
+}
+devices(){
+    echo "WARNING: This command should only be used when picking a device for usage with 'set'"
+    curl -X "GET" "https://api.spotify.com/v1/me/player/devices" -H "Accept: application/json" -H "Content-Type: application/json" -H "Authorization: Bearer  $AUTHKEY" -s | jq -M '.devices'
 }
 set_volume(){
     curl -s -X PUT -d device_id=$id -H "Accept: application/json" -H "Content-Type: application/json" -H "Authorization: Bearer $AUTHKEY" "https://api.spotify.com/v1/me/player/volume?volume_percent=$2"
@@ -83,12 +87,18 @@ repeat_off(){
 repeat_state(){
     get_info | jq -M 'del(.["device", "actions", "external_urls", "track_number", "preview_url", "popularity", "name", "uri", "href", "id", "is_local", "item", "shuffle_state", "is_playing", "timestamp", "context", "progress_ms", "currently_playing_type"])' | sed -e 's/{//g' -e 's/\}//g' -e '/^[[:space:]]*$/d' |  sed 's/://g' | jq -M -r | tr "\n" " " |sed -e 's/^[ \t]*//;s/[ \t]*$//' | tr " " ":" | sed -e 's/repeat_state/Repeat/g' -e 's/:/: /g' && echo ''
 }
+set(){
+    curl -X "PUT" "https://api.spotify.com/v1/me/player" --data "{\"device_ids\":[\"$2\"]}" -H "Accept: application/json" -H "Content-Type: application/json" -H "Authorization: Bearer $AUTHKEY"
+}
 help(){
 		cat << EOF
 ${0##*/}: Spotify Control API ~ Written in bash
-Usage: ${0##*/}: [auth|devices|search_play|search|play_track|get_volume|set_volume|get_info|previous|skip|pause|resume|loop|repeat|state]
+Usage: ${0##*/}:
+[auth|device|search_play|search|play_track|get_volume|set_volume|get_info|previous|skip|pause|resume|loop|repeat|state|set]
+***
 auth: Print AUTHKEY and exit
-devices: Print first device ID and exit
+device: Print first device ID and exit
+devices: List ALL devices and exit
 search_play: Search for "arg2" and play
 search: Search for "arg2" and output URI & NAME
 play_track: Play URI
@@ -104,6 +114,8 @@ repeat: Repeat current album/playlist
 state: Output playback status and exit
 repeat_off: Disable loop/repeat
 repeat_state: Output playback repeat status and exit
+set: Move playback to "arg2" | "arg2" must be a device ID
+***
 EOF
 }
 auth
@@ -122,3 +134,7 @@ if [ $1 = "search_play" ]; then
     exit 0
 fi
 ${1} $@
+if [ $? != "0" ]; then
+    echo "ERROR: Something went wrong!"
+    echo "A device may not currently be seleted"
+fi
