replace tabs for spaces, fix help()

diff --git a/spotbash b/spotbash
--- a/spotbash
+++ b/spotbash
@@ -2,43 +2,43 @@
 # First run
 [ -d "${XDG_CACHE_HOME:-$HOME/.cache/}/spotbash/" ] || mkdir -p "${XDG_CACHE_HOME:-$HOME/.cache/}/spotbash/"
 { [ -f ./spinner/spinner.sh ] && [ ! -f "${XDG_CACHE_HOME:-$HOME/.cache/}/spotbash/spinner.sh"]; } && {
-	 mv ./spinner/spinner.sh "${XDG_CACHE_HOME:-$HOME/.cache/}/spotbash/"
-	 sed 's/SPINNER_SYMBOLS=.*/SPINNER_SYMBOLS="WIDE_ASCII_PROG"/' -i "${XDG_CACHE_HOME:-$HOME/.cache/}/spotbash/spinner.sh" # Cache spinner
-	 sed 's,SPINNER_DONEFILE=.*,SPINNER_DONEFILE=~/ends,' -i "${XDG_CACHE_HOME:-$HOME/.cache/}/spotbash/spinner.sh"
+   mv ./spinner/spinner.sh "${XDG_CACHE_HOME:-$HOME/.cache/}/spotbash/"
+   sed 's/SPINNER_SYMBOLS=.*/SPINNER_SYMBOLS="WIDE_ASCII_PROG"/' -i "${XDG_CACHE_HOME:-$HOME/.cache/}/spotbash/spinner.sh" # Cache spinner
+   sed 's,SPINNER_DONEFILE=.*,SPINNER_DONEFILE=~/ends,' -i "${XDG_CACHE_HOME:-$HOME/.cache/}/spotbash/spinner.sh"
 }
 ##
 has() {
-	case "$(command -v $1 2>/dev/null)" in
-		alias*|"") return 1
-	esac
+  case "$(command -v $1 2>/dev/null)" in
+    alias*|"") return 1
+  esac
 }
 deps() {
   deps="jq curl" # Make sure deps can be found
   for i in $deps; do
-  	if ! has $i; then
-  		echo "$i IS MISSING!"; missing=$(($missing + 1))
-  	fi
+    if ! has $i; then
+      echo "$i IS MISSING!"; missing=$(($missing + 1))
+    fi
   done
   [ ${missing:-0} -gt 0 ] || {
     [ ${missing:-0} -gt 1 ] && {
       echo "JQ AND CURL ARE MISSING!"; exit 1
     } || {
       for i in $deps; do
-      	if ! has $i; then
-      		echo "$i IS MISSING!"; exit 1
-      	fi
+        if ! has $i; then
+          echo "$i IS MISSING!"; exit 1
+        fi
       done
     }
-	}
-	# Check for ssl
-	curl -V | grep tls -i -q || {
-		curl -V | grep ssl -i -q || {
-			echo "!!SSL/TLS SUPPORT IS MISSING FROM CURL!!"
-			echo "!!SPOTBASH REQUIRES SSL SUPPORT!!"
-			exit 1
-		}
-	}
-	#
+  }
+  # Check for ssl
+  curl -V | grep tls -i -q || {
+    curl -V | grep ssl -i -q || {
+      echo "!!SSL/TLS SUPPORT IS MISSING FROM CURL!!"
+      echo "!!SPOTBASH REQUIRES SSL SUPPORT!!"
+      exit 1
+    }
+  }
+  #
   export missing="no" # Finaly set missing to no - We can check this variable, instead of calling deps()
 }
 clean_up(){
@@ -53,7 +53,7 @@ auth() {
       echo "ERROR: The AUTHKEYS cache file is missing!! Spotbash needs this file.. If you don't have it, reclone and re-run the setup"; exit 1
     }
   else
-  	. "${XDG_CACHE_HOME:-$HOME/.cache/}/spotbash/authkeys"
+    . "${XDG_CACHE_HOME:-$HOME/.cache/}/spotbash/authkeys"
   fi
   AUTHKEY=$(curl -X POST -d grant_type=refresh_token -d refresh_token="$REKEY" -d client_id="$CLID" -d client_secret="$CLSEC" https://accounts.spotify.com/api/token -s | jq .access_token -r)
   export AUTHKEY; export AUTHD="1"
@@ -158,9 +158,9 @@ play(){
 }
 trans(){
     [ ! -z $2 ] && {
-	     export TRANS_ID=${2}
+       export TRANS_ID=${2}
     } || {
-	     export TRANS_ID=$id
+       export TRANS_ID=$id
     }
     curl -X "PUT" "https://api.spotify.com/v1/me/player" --data "{\"device_ids\":[\"${TRANS_ID}\"]}" -H "Accept: application/json" -H "Content-Type: application/json" -H "Authorization: Bearer $AUTHKEY"
 }
@@ -190,9 +190,9 @@ shuffle() {
 }
 # Songs func would go here - Spot(y)RIP is overkill, prob will add a rip function
 download() {
-	has youtube-dl && {
-		youtube-dl ytsearch1:"$(name | sed -e 's/.*: //g' -e 's/\,.*//' | tr '\n' ' ')" $([ "$1" = "download" ] &&  echo $@ | cut -d' ' -f2-)
-	} || {
+  has youtube-dl && {
+    youtube-dl ytsearch1:"$(name | sed -e 's/.*: //g' -e 's/\,.*//' | tr '\n' ' ')" $([ "$1" = "download" ] &&  echo $@ | cut -d' ' -f2-)
+  } || {
     echo "youtube-dl is missing!"; exit 1
   }
 }
@@ -212,44 +212,44 @@ prev(){
     pre
 }
 length() {
-		curl -X "GET" "https://api.spotify.com/v1/playlists/$2/tracks?market=US" -H "Accept: application/json" -H "Content-Type: application/json" -H "Authorization: Bearer $AUTHKEY" -s | jq .total -Mr
+    curl -X "GET" "https://api.spotify.com/v1/playlists/$2/tracks?market=US" -H "Accept: application/json" -H "Content-Type: application/json" -H "Authorization: Bearer $AUTHKEY" -s | jq .total -Mr
 }
 rip() {
-		len="$(length - $2)" # - Is placeholder
-		has youtube-dl && {
-			echo "Working..."
-			[ -f "${XDG_CACHE_HOME:-$HOME/.cache/}/spotbash/spinner.sh" ] && {
-				. "${XDG_CACHE_HOME:-$HOME/.cache/}/spotbash/spinner.sh"
-				spinner &
-				PID=$!
-			} || {
-				echo "spinner.sh cache missing... (No progress-bar)"
-				echo "Please wait..."
-			}
-			trap '[ -f ${XDG_CACHE_HOME:-$HOME/.cache/}/spotbash/spinner.sh ] && { kill $PID; exit 1 ; } || exit 1' INT TERM
-			for i in $(seq $len); do
-				youtube-dl ytsearch1:"$(curl -X "GET" "https://api.spotify.com/v1/playlists/$2/tracks?market=US&limit=1&offset=$i" -H "Accept: application/json" -H "Content-Type: application/json" -H "Authorization: Bearer $AUTHKEY" -s | jq '.items[].track | .name,.artists[].name ' -r | tr '\n' ' ')"
-			done
-			[ -f "${XDG_CACHE_HOME:-$HOME/.cache/}/spotbash/spinner.sh" ] && {
-				kill $PID
-			}
+    len="$(length - $2)" # - Is placeholder
+    has youtube-dl && {
+      echo "Working..."
+      [ -f "${XDG_CACHE_HOME:-$HOME/.cache/}/spotbash/spinner.sh" ] && {
+        . "${XDG_CACHE_HOME:-$HOME/.cache/}/spotbash/spinner.sh"
+        spinner &
+        PID=$!
+      } || {
+        echo "spinner.sh cache missing... (No progress-bar)"
+        echo "Please wait..."
+      }
+      trap '[ -f ${XDG_CACHE_HOME:-$HOME/.cache/}/spotbash/spinner.sh ] && { kill $PID; exit 1 ; } || exit 1' INT TERM
+      for i in $(seq $len); do
+        youtube-dl ytsearch1:"$(curl -X "GET" "https://api.spotify.com/v1/playlists/$2/tracks?market=US&limit=1&offset=$i" -H "Accept: application/json" -H "Content-Type: application/json" -H "Authorization: Bearer $AUTHKEY" -s | jq '.items[].track | .name,.artists[].name ' -r | tr '\n' ' ')"
+      done
+      [ -f "${XDG_CACHE_HOME:-$HOME/.cache/}/spotbash/spinner.sh" ] && {
+        kill $PID
+      }
     } || { echo "youtube-dl is required for rip()... Please install it"; exit 1; }
 }
 ####################################################################################
 ####################################################################################
 help() {
-	cat << EOF
+  cat << EOF
 ***
 Spotbash: Spotify Control API ~ Written in bash ~ By ThatGeekyWeeb (Mia)
 ***
-[auth] - Print ${AUTHKEY:-'$AUTHKEY'} and exit
+[auth] - Print ${AUTHKEY:-'\$AUTH KEY'} and exit
 [device] - Print first device ID and exit
 [devices] - List ALL devices and exit
-[search_play] - Search for ${2:-'$2'} and play | ${2:-'$2'} must be a track
-[search_track] - Search for ${2:-'$2'} and output URI & Artist & name | ${2:-'$2'} is interpreted as a track
+[search_play] - Search for ${2:-'\$2'} and play | ${2:-'\$2'} must be a track
+[search_track] - Search for ${2:-'\$2'} and output URI & Artist & name | ${2:-'\$2'} is interpreted as a track
 [play_track] - Play Track URI
 [get_volume] - Output player volume and exit
-[set_volume] - Set player volume to ${2:-'$2'} and exit
+[set_volume] - Set player volume to ${2:-'\$2'} and exit
 [get_info] - Get debugging info about currently playing device
 [pre | prev | previous] - Change playback to previous song
 [skip | next] - Change playback to next song
@@ -261,57 +261,57 @@ Spotbash: Spotify Control API ~ Written in bash ~ By ThatGeekyWeeb (Mia)
 [repeat_off] - Disable loop/repeat
 [repeat_state] - Output playback repeat status and exit
 [playlists] - Output list of users playlists and exit
-[play] - Play ${2:-'$2'} | ${2:-'$2'} must be Album or Playlist URI
+[play] - Play ${2:-'\$2'} | ${2:-'\$2'} must be Album or Playlist URI
 [playing] - Print Song name followed by artist and exit
 [left] - Print time left in MS (exact) and exit
 [minleft] - Print time left in Mins (approximate) and exit
-[shuffle] - Enable/Disable Shuffle | Set to ${2:-'$2'} if specified
+[shuffle] - Enable/Disable Shuffle | Set to ${2:-'\$2'} if specified
 [shuffle_state] - Print state of shuffle and exit
-[download] - Download currently playing song using ytdl | "${@:-'$@'}" are ytdl flags
+[download] - Download currently playing song using ytdl | "${@:-'\$@'}" are ytdl flags
 EOF
 }
 ####################################################################################
 ####################################################################################
 clean_up
 deps && {
-	auth && get_info && id
+  auth && get_info && id
 } || {
-	exit 1
+  exit 1
 }
 case $1 in
-		help)
-				help; exit 1
-				;;
+    help)
+        help; exit 1
+        ;;
     auth)
         echo "$AUTHKEY" && clean_up; exit 0
         ;;
-		get_info)
-				cat "$infoF"; exit 0
-				;;
+    get_info)
+        cat "$infoF"; exit 0
+        ;;
     search_play)
-	 		auth
-	 		export id
-	 		printf "search='%b'" "${2}" > "${XDG_CACHE_HOME:-$HOME/.cache/}/spotbash/search"
-	 		sed -i -e 's/[[:space:]]/%20/g' "${XDG_CACHE_HOME:-$HOME/.cache/}/spotbash/search"
-	 		uri=$(search_track | cut -d'@' -f2- | cut -d$'\n' -f1 | sed 's/[[:space:]]//g')
-	 		printf "uri='%b'" "${uri}" > "${XDG_CACHE_HOME:-$HOME/.cache/}/spotbash/uri"
-	 		play_track "$@"
-	 		clean_up
-	 		exit 0
-	 		;;
+       auth
+       export id
+       printf "search='%b'" "${2}" > "${XDG_CACHE_HOME:-$HOME/.cache/}/spotbash/search"
+       sed -i -e 's/[[:space:]]/%20/g' "${XDG_CACHE_HOME:-$HOME/.cache/}/spotbash/search"
+       uri=$(search_track | cut -d'@' -f2- | cut -d$'\n' -f1 | sed 's/[[:space:]]//g')
+       printf "uri='%b'" "${uri}" > "${XDG_CACHE_HOME:-$HOME/.cache/}/spotbash/uri"
+       play_track "$@"
+       clean_up
+       exit 0
+       ;;
     "")
-			help && clean_up; exit 1
-			;;
+      help && clean_up; exit 1
+      ;;
     *)
-			type ${1} 2>&1 1>/dev/null && {
-				${1} "$@" || {
-					echo "Whoops! Something went wrong..."
-				} && {
-					clean_up; exit 0
-				}
-			}	|| {
-				help; clean_up; exit 1
-			}
-			clean_up
+      type ${1} 2>&1 1>/dev/null && {
+        ${1} "$@" || {
+          echo "Whoops! Something went wrong..."
+        } && {
+          clean_up; exit 0
+        }
+      }  || {
+        help; clean_up; exit 1
+      }
+      clean_up
       ;;
 esac
